### ISSUE TITLE
Max Depth option for RDF::RDFXML::Writer?

### ISSUE THREAD

**Issue by kardeiz** [ruby-rdf/rdf-rdfxml#27]
Does `v. 1.1.1.1` provide the `max_depth` option for `RDF::RDFXML::Writer`? For example:

    puts RDF::RDFXML::Writer.buffer(:max_depth => 100) { |w| w << graph }

I've looked around this repository and `rdf-1.1.1.1/lib/rdf/writer.rb` and I don't see it. 

If it's no longer available, are there alternatives for formatting the serialized RDFXML?

**Comment by gkellogg** [comment]
Better late than never, sorry it took me so long to get to this.
