### ISSUE TITLE
Vocabulary generation error

### ISSUE THREAD

**Issue by dchandekstark** [ruby-rdf/rdf-rdfxml#35]
Attempting to generate an RDF::StrictVocabulary from http://rs.tdwg.org/dwc/rdf/dwcterms.rdf using  RDF::VocabularyLoader.

See projecthydra-labs/rdf-vocab#35 for details.

**Comment by gkellogg** [comment]
See how that works for you; note that it's on the develop branch, and not yet released to rubygems. You should be able to clone the ruby-gems gem and add a line to pull from develop to test out. I'll likely release an update of the gem next week.

You can also try by cloning the rdf-rdfxml gem and parsing using `script/parse` using your URL.

cc/ @jhallida @jcoyne @no-reply @barmintor @terrellt
